// QB Data - Part 1: Top 25 Quarterbacks
const qbData = [
    {
        name: "Josh Allen",
        team: "BUF",
        age: 29,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 10,
        points2024: 445,
        points2024Score: 10,
        ppg2024: 26.2,
        ppg2024Score: 10,
        projPoints2025: 377,
        projPointsScore: 10,
        projPPG2025: 22.2,
        projPPGScore: 10,
        olRank: 8,
        offProjRank: 10,
        wrCorpsRank: 7
    },
    {
        name: "Lamar Jackson",
        team: "BAL",
        age: 28,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 10,
        points2024: 421,
        points2024Score: 10,
        ppg2024: 24.8,
        ppg2024Score: 10,
        projPoints2025: 376,
        projPointsScore: 10,
        projPPG2025: 22.1,
        projPPGScore: 10,
        olRank: 7,
        offProjRank: 10,
        wrCorpsRank: 8
    },
    {
        name: "Jalen Hurts",
        team: "PHI",
        age: 26,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 9,
        points2024: 389,
        points2024Score: 9,
        ppg2024: 22.9,
        ppg2024Score: 9,
        projPoints2025: 359,
        projPointsScore: 9,
        projPPG2025: 21.1,
        projPPGScore: 9,
        olRank: 10,
        offProjRank: 9,
        wrCorpsRank: 10
    },
    {
        name: "Jayden Daniels",
        team: "WAS",
        age: 25,
        ageScore: 9,
        injury: "Healthy",
        healthScore: 9,
        points2024: 378,
        points2024Score: 9,
        ppg2024: 22.2,
        ppg2024Score: 8,
        projPoints2025: 355,
        projPointsScore: 9,
        projPPG2025: 20.9,
        projPPGScore: 9,
        olRank: 7,
        offProjRank: 8,
        wrCorpsRank: 8
    },
    {
        name: "Joe Burrow",
        team: "CIN",
        age: 28,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 8,
        points2024: 367,
        points2024Score: 8,
        ppg2024: 21.6,
        ppg2024Score: 8,
        projPoints2025: 341,
        projPointsScore: 8,
        projPPG2025: 20.1,
        projPPGScore: 8,
        olRank: 6,
        offProjRank: 9,
        wrCorpsRank: 9
    },
    {
        name: "Patrick Mahomes II",
        team: "KC",
        age: 29,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 9,
        points2024: 334,
        points2024Score: 7,
        ppg2024: 19.6,
        ppg2024Score: 7,
        projPoints2025: 329,
        projPointsScore: 7,
        projPPG2025: 19.4,
        projPPGScore: 7,
        olRank: 6,
        offProjRank: 8,
        wrCorpsRank: 7
    },
    {
        name: "Baker Mayfield",
        team: "TB",
        age: 29,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 9,
        points2024: 356,
        points2024Score: 8,
        ppg2024: 21.0,
        ppg2024Score: 8,
        projPoints2025: 322,
        projPointsScore: 7,
        projPPG2025: 18.9,
        projPPGScore: 7,
        olRank: 8,
        offProjRank: 9,
        wrCorpsRank: 9
    },
    {
        name: "Kyler Murray",
        team: "ARI",
        age: 27,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 7,
        points2024: 298,
        points2024Score: 6,
        ppg2024: 17.5,
        ppg2024Score: 6,
        projPoints2025: 317,
        projPointsScore: 7,
        projPPG2025: 18.7,
        projPPGScore: 7,
        olRank: 5,
        offProjRank: 6,
        wrCorpsRank: 6
    },
    {
        name: "Brock Purdy",
        team: "SF",
        age: 25,
        ageScore: 9,
        injury: "Healthy",
        healthScore: 8,
        points2024: 287,
        points2024Score: 6,
        ppg2024: 16.9,
        ppg2024Score: 6,
        projPoints2025: 311,
        projPointsScore: 7,
        projPPG2025: 18.3,
        projPPGScore: 7,
        olRank: 7,
        offProjRank: 9,
        wrCorpsRank: 7
    },
    {
        name: "Bo Nix",
        team: "DEN",
        age: 25,
        ageScore: 9,
        injury: "Healthy",
        healthScore: 9,
        points2024: 289,
        points2024Score: 6,
        ppg2024: 17.0,
        ppg2024Score: 6,
        projPoints2025: 309,
        projPointsScore: 7,
        projPPG2025: 18.2,
        projPPGScore: 7,
        olRank: 9,
        offProjRank: 7,
        wrCorpsRank: 6
    },
    {
        name: "Justin Fields",
        team: "NYJ",
        age: 26,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 8,
        points2024: 276,
        points2024Score: 6,
        ppg2024: 16.2,
        ppg2024Score: 5,
        projPoints2025: 301,
        projPointsScore: 6,
        projPPG2025: 17.7,
        projPPGScore: 6,
        olRank: 5,
        offProjRank: 5,
        wrCorpsRank: 5
    },
    {
        name: "J.J. McCarthy",
        team: "MIN",
        age: 22,
        ageScore: 5,
        injury: "Healthy",
        healthScore: 8,
        points2024: 0,
        points2024Score: 1,
        ppg2024: 0,
        ppg2024Score: 1,
        projPoints2025: 292,
        projPointsScore: 6,
        projPPG2025: 17.2,
        projPPGScore: 6,
        olRank: 6,
        offProjRank: 6,
        wrCorpsRank: 8
    },
    {
        name: "Dak Prescott",
        team: "DAL",
        age: 31,
        ageScore: 8,
        injury: "Healthy",
        healthScore: 7,
        points2024: 245,
        points2024Score: 5,
        ppg2024: 14.4,
        ppg2024Score: 4,
        projPoints2025: 292,
        projPointsScore: 6,
        projPPG2025: 17.2,
        projPPGScore: 6,
        olRank: 6,
        offProjRank: 6,
        wrCorpsRank: 7
    },
    {
        name: "Justin Herbert",
        team: "LAC",
        age: 26,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 8,
        points2024: 267,
        points2024Score: 5,
        ppg2024: 15.7,
        ppg2024Score: 5,
        projPoints2025: 291,
        projPointsScore: 6,
        projPPG2025: 17.1,
        projPPGScore: 6,
        olRank: 5,
        offProjRank: 7,
        wrCorpsRank: 6
    },
    {
        name: "Jared Goff",
        team: "DET",
        age: 30,
        ageScore: 9,
        injury: "Healthy",
        healthScore: 9,
        points2024: 312,
        points2024Score: 7,
        ppg2024: 18.4,
        ppg2024Score: 7,
        projPoints2025: 288,
        projPointsScore: 6,
        projPPG2025: 17.0,
        projPPGScore: 6,
        olRank: 8,
        offProjRank: 9,
        wrCorpsRank: 10
    },
    {
        name: "Caleb Williams",
        team: "CHI",
        age: 23,
        ageScore: 6,
        injury: "Healthy",
        healthScore: 9,
        points2024: 234,
        points2024Score: 4,
        ppg2024: 13.8,
        ppg2024Score: 4,
        projPoints2025: 287,
        projPointsScore: 6,
        projPPG2025: 16.9,
        projPPGScore: 6,
        olRank: 8,
        offProjRank: 6,
        wrCorpsRank: 7
    },
    {
        name: "C.J. Stroud",
        team: "HOU",
        age: 23,
        ageScore: 6,
        injury: "Healthy",
        healthScore: 9,
        points2024: 267,
        points2024Score: 5,
        ppg2024: 15.7,
        ppg2024Score: 5,
        projPoints2025: 280,
        projPointsScore: 5,
        projPPG2025: 16.5,
        projPPGScore: 5,
        olRank: 3,
        offProjRank: 5,
        wrCorpsRank: 7
    },
    {
        name: "Jordan Love",
        team: "GB",
        age: 26,
        ageScore: 10,
        injury: "Thumb Injury",
        healthScore: 7,
        points2024: 289,
        points2024Score: 6,
        ppg2024: 17.0,
        ppg2024Score: 6,
        projPoints2025: 278,
        projPointsScore: 5,
        projPPG2025: 16.4,
        projPPGScore: 5,
        olRank: 7,
        offProjRank: 7,
        wrCorpsRank: 6
    },
    {
        name: "Drake Maye",
        team: "NE",
        age: 22,
        ageScore: 5,
        injury: "Healthy",
        healthScore: 8,
        points2024: 187,
        points2024Score: 3,
        ppg2024: 11.0,
        ppg2024Score: 3,
        projPoints2025: 276,
        projPointsScore: 5,
        projPPG2025: 16.2,
        projPPGScore: 5,
        olRank: 2,
        offProjRank: 4,
        wrCorpsRank: 3
    },
    {
        name: "Trevor Lawrence",
        team: "JAC",
        age: 26,
        ageScore: 10,
        injury: "Healthy",
        healthScore: 7,
        points2024: 234,
        points2024Score: 4,
        ppg2024: 13.8,
        ppg2024Score: 4,
        projPoints2025: 275,
        projPointsScore: 5,
        projPPG2025: 16.2,
        projPPGScore: 5,
        olRank: 2,
        offProjRank: 5,
        wrCorpsRank: 6
    },
    {
        name: "Bryce Young",
        team: "CAR",
        age: 23,
        ageScore: 6,
        injury: "Healthy",
        healthScore: 8,
        points2024: 156,
        points2024Score: 3,
        ppg2024: 9.2,
        ppg2024Score: 2,
        projPoints2025: 264,
        projPointsScore: 5,
        projPPG2025: 15.5,
        projPPGScore: 5,
        olRank: 4,
        offProjRank: 4,
        wrCorpsRank: 5
    },
    {
        name: "Michael Penix Jr.",
        team: "ATL",
        age: 24,
        ageScore: 7,
        injury: "Healthy",
        healthScore: 8,
        points2024: 0,
        points2024Score: 1,
        ppg2024: 0,
        ppg2024Score: 1,
        projPoints2025: 263,
        projPointsScore: 5,
        projPPG2025: 15.5,
        projPPGScore: 5,
        olRank: 6,
        offProjRank: 6,
        wrCorpsRank: 7
    },
    {
        name: "Tua Tagovailoa",
        team: "MIA",
        age: 27,
        ageScore: 10,
        injury: "Concussion History",
        healthScore: 5,
        points2024: 198,
        points2024Score: 3,
        ppg2024: 11.6,
        ppg2024Score: 3,
        projPoints2025: 263,
        projPointsScore: 5,
        projPPG2025: 15.5,
        projPPGScore: 5,
        olRank: 3,
        offProjRank: 5,
        wrCorpsRank: 6
    },
    {
        name: "Matthew Stafford",
        team: "LAR",
        age: 36,
        ageScore: 4,
        injury: "Back Issues",
        healthScore: 6,
        points2024: 267,
        points2024Score: 5,
        ppg2024: 15.7,
        ppg2024Score: 5,
        projPoints2025: 262,
        projPointsScore: 5,
        projPPG2025: 15.4,
        projPPGScore: 5,
        olRank: 5,
        offProjRank: 7,
        wrCorpsRank: 8
    }
];

// Function to populate QB data table
function populateQBData() {
    const tbody = document.getElementById('qb-data');
    if (!tbody) {
        console.error('QB data table body not found');
        return;
    }
    
    // Calculate final scores for each QB
    const scoreFields = ['ageScore', 'healthScore', 'points2024Score', 'ppg2024Score', 'projPointsScore', 'projPPGScore', 'olRank', 'offProjRank', 'wrCorpsRank'];
    
    const sortedQBs = qbData.map(qb => ({
        ...qb,
        finalScore: calculateFinalScore(qb, scoreFields)
    })).sort((a, b) => b.finalScore - a.finalScore);
    
    tbody.innerHTML = sortedQBs.map(qb => `
        <tr>
            <td class="player-name">${qb.name}</td>
            <td class="team">${qb.team}</td>
            <td>${qb.age}</td>
            <td class="${getScoreClass(qb.ageScore)}">${qb.ageScore}</td>
            <td><span class="injury-status ${getInjuryClass(qb.injury)}">${qb.injury}</span></td>
            <td class="${getScoreClass(qb.healthScore)}">${qb.healthScore}</td>
            <td>${qb.points2024}</td>
            <td class="${getScoreClass(qb.points2024Score)}">${qb.points2024Score}</td>
            <td>${qb.ppg2024}</td>
            <td class="${getScoreClass(qb.ppg2024Score)}">${qb.ppg2024Score}</td>
            <td>${qb.projPoints2025}</td>
            <td class="${getScoreClass(qb.projPointsScore)}">${qb.projPointsScore}</td>
            <td>${qb.projPPG2025}</td>
            <td class="${getScoreClass(qb.projPPGScore)}">${qb.projPPGScore}</td>
            <td class="${getScoreClass(qb.olRank)}">${qb.olRank}</td>
            <td class="${getScoreClass(qb.offProjRank)}">${qb.offProjRank}</td>
            <td class="${getScoreClass(qb.wrCorpsRank)}">${qb.wrCorpsRank}</td>
            <td class="final-score">${qb.finalScore}</td>
        </tr>
    `).join('');
}
